<?php

function angular_demo_menu() {
  $items = [];
  $items['angular2'] = [
    'access callback' => TRUE,
    'page callback' => 'angular_demo_callback',
  ];
  return $items;
}

function angular_demo_theme($existing, $type, $theme, $path) {
  return [
    'angular_component' => [
      'template' => 'angular-component',
      'variables' => array(),
      'path' => drupal_get_path('module', 'angular_demo') . '/theme',
    ],
  ];
}

function angular_demo_callback() {
  $build = [];

  $build['content'] = [
    '#theme' => [
      'angular_component',
    ],
    '#attached' => [
      'js' => [
        libraries_get_path('node_modules') . '/core-js/client/shim.min.js',
        libraries_get_path('node_modules') . '/zone.js/dist/zone.js',
        libraries_get_path('node_modules') . '/reflect-metadata/Reflect.js',
        libraries_get_path('node_modules') . '/rxjs/bundles/Rx.js',
        libraries_get_path('node_modules') . '/@angular/core/bundles/core.umd.js',
        libraries_get_path('node_modules') . '/@angular/common/bundles/common.umd.js',
        libraries_get_path('node_modules') . '/@angular/compiler/bundles/compiler.umd.js',
        libraries_get_path('node_modules') . '/@angular/platform-browser/bundles/platform-browser.umd.js',
        libraries_get_path('node_modules') . '/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
        drupal_get_path('module', 'angular_demo') . '/angular_demo.component.js',
        drupal_get_path('module', 'angular_demo') . '/angular_demo.module.js',
        drupal_get_path('module', 'angular_demo') . '/angular_demo.main.js',
      ],
    ],
  ];

  return $build;
}
